name: Cleanup Old Workflow Runs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  cleanup:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          older_than_seconds: 0
          minimum_runs_to_keep: 20
